### ISSUE TITLE
Can I feed shell command output?

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/rssa#1]
I have a small shell script (actually written in ruby) that fetches some data from private API using private access tokens. I don't want to expose this data anywhere on the internet. I'd love to be able to use rssa to create a dashboard for the output of this script. Any way I can use shell instead of Google Chrome?

**Comment by vfonic** [comment]
I see I might use this:
https://github.com/fabiospampinato/rssa/blob/691df235f21887aee9b4ab051aafaee889cf6d51/src/fetch.ts#L18

Or first run my script and store it as a cache for rssa.

What do you suggest?

**Comment by fabiospampinato** [comment]
I'm not sure, perhaps you could run an arbitrary command that writes a file somewhere and then tell rssa to load `file:///foo/bar.txt` or something.

I don't think you can currently use rssa for websites that require some cookie to be set etc. 🤔

**Comment by vfonic** [comment]
The above line, that I linked, actually executes shell script and takes its output. I have a shell script that creates the output. That should work, right?

I could ignore arguments like `--headless` or I could also just submit a PR with one more config: `shell_arguments`. This would default to `--headless --disable-gpu --dump-dom`. Then I can have the script call `ruby ${url}`, where `url` would be a path to my script. 🤔 

That might be quite some changes. I guess at that point it wouldn't make sense to call the config variable `chrome_path`.
